### ISSUE TITLE
Do you have example about use QR500 for drive?

### ISSUE THREAD

**Issue by haisaco** [MuaazH/ZKTeco_PULLSDK_Wrapper#1]
Can I know what is AccessPanel use QR500?

**Comment by MuaazH** [comment]
QR500 is not an Access Panel. It's just a card reader that is meant to be connected to an access panel. I could be wrong, the idiots from ZKTeco gave a very poor description and no datasheet for the product.

**Comment by MuaazH** [comment]
You should have a control panel somewhere else, can you describe your setup?

**Comment by haisaco** [comment]
I have 4 devices, each with a QR code reader.
I create a separate database to store accessible QR code information.
I use DllImport("plcommpro.dll").
First I "Connect" drive
then use GetRTLog to get the information returned when the user uses the QR.
I then examine the data in the database to make a decision to open the door.
Currently my code is getting quite a lot of errors related to processing between threads.

**Comment by MuaazH** [comment]
If you've gotten that far, you may as well use [AccessPanel.GetEventLog](https://github.com/MuaazH/ZKTeco_PULLSDK_Wrapper/blob/c15ba01e4713b2cf8d8bb0270c15a8fe5d8da08d/PullSDK_core/AccessPanel.cs#L924). The example on how to connect is on [README](https://github.com/MuaazH/ZKTeco_PULLSDK_Wrapper/blob/c15ba01e4713b2cf8d8bb0270c15a8fe5d8da08d/README.md#how-to-use-pull-sdk)

**Comment by MuaazH** [comment]
Closed for inactivity.

**Comment by haisaco** [comment]
Thanks you.
I have a question. I want to set time pending for open door, do you know where it is?
I see when I call OpenDoor it is open about 5s. I want to set wait open about 10s.

**Comment by MuaazH** [comment]
Change the `5` to `10`.
The 1st parameter is the door id. Example: 1, 2, 3...
The 2nd parameter is time in seconds. Max is 60 seconds.

**Comment by haisaco** [comment]
2nd it's waiting time between 2 gate openings. It's not the waiting time to open the gate until someone comes through.
I want to increase the open wait time until someone passes by

**Comment by MuaazH** [comment]
Are you sure? I only worked with these device remotely, I could've been mislead. Even the documentation is misleading in that case.

**Comment by MuaazH** [comment]
> Param3
[in]: When the OperationID is output operation, the parameter indicates the door-opening time (0 indicates the closed state, 255 indicates the normal open state, the value range is 1 to 60 seconds). The default value is 0.

[The bad, ugly documentation](https://github.com/MuaazH/ZKTeco_PULLSDK_Wrapper/blob/main/PullSDK%20User%20Guide-EN%20V2.0-201201.doc)

**Comment by MuaazH** [comment]
take the last version of the code and try calling openDoor with 255. It should leave the door open forever. Then call closeDoor when you want to close it. That could be it.

**Comment by MuaazH** [comment]
Closed for inactivity.
