### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by iiluxs** [MuaazH/ZKTeco_PULLSDK_Wrapper#2]
I am trying to install it but it kept closing the doors.
Could you provide more details about the intallation process.

all respect.

**Comment by MuaazH** [comment]
> Could you provide more details about the intallation process.
1. What do you mean by "installation"? this is a library, you don't install it, you include it in your own application. Do you mean how to include it? Or how to use it (i.e. API Doc)

> I am trying to install it but it kept closing the doors.
2. This is a library, it does not do anything. It just offers you the API to do things yourself.
(PS: Feel free to speak Arabic if you can)

**Comment by MuaazH** [comment]
Closed for inactivity.
