### ISSUE TITLE
how to use in asp.net blazor??? can u write code for me

### ISSUE THREAD

**Issue by Mr-Sunshinexplorer** [MuaazH/ZKTeco_PULLSDK_Wrapper#4]
Device name is zkteco k60 Fingerprint access control

**Comment by MuaazH** [comment]
> How to use in asp.net blazor?

The same way you use in any C# app.

> Can you write code for me

Yes, I can, that's my job. My rate is $60 per hour, but I'm not available at the moment. Try again in a month.
[Read this](https://github.com/MuaazH/ZKTeco_PULLSDK_Wrapper?tab=readme-ov-file#zkteco-pullsdk-wrapper).
